#Name of the workflow
name: Code

#when the workflow should run
on:
  workflow_call:

#jobs in thw workflow
jobs:
  code-checkout:
    runs-on: self-hosted
    #steps in the workflow
    steps:
      - name: Clone the code
        uses: actions/checkout@v7
      - name: Print the message
        run: echo "Code Cloned"
